import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ChangeEvent, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [price, setPrice] = useState('')
  const [goldheart, setGoldheart] = useState('')

  const replace = 'EGULDHJÆRT'.split('')

  const priceChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPrice(e.target.value)

    if (e.target.value !== '') {
      const goldheart = e.target.value
        .split('')
        .map((d) => (d == '.' ? ',' : replace[+d]))
        .join('')

      setGoldheart(goldheart)
    } else {
      setGoldheart('')
    }
  }

  const heartChange = (e: ChangeEvent<HTMLInputElement>) => {
    setGoldheart(e.target.value.toUpperCase())

    if (e.target.value !== '') {
      const goldheart = e.target.value
        .toUpperCase()
        .split('')
        .filter((d) => replace.indexOf(d) != -1)
        .map((d) => (d == ',' ? null : replace.indexOf(d)))
        .join('')

      setPrice(goldheart)
    } else {
      setPrice('')
    }
  }

  return (
    <>
      <Head>
        <title>Guldhjerte 💛</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="m-auto">
          <h1 className="text-lg font-medium text-center mb-4">
            Guldhjerte koder 💛
          </h1>
          <div className="flex">
            <div className="text-center mr-4">
              <p className="font-medium text-gray-800">Pris</p>
              <input
                type="text"
                className="rounded-md mr-2 border-gray-300 border p-1"
                value={price}
                onChange={priceChange}
              />
            </div>

            <div className="text-center">
              <p className="font-medium text-gray-800">Kode</p>
              <input
                type="text"
                className="rounded-md border-gray-300 border p-1"
                value={goldheart}
                onChange={heartChange}
              />
            </div>
          </div>
          <div className="mt-4 text-center">
            <a
              href="https://github.com/Admiral-Enigma"
              className="text-gray-400  text-sm font-medium"
            >
              Made by Alexander
            </a>
          </div>
        </div>
      </div>
    </>
  )
}
